import os
import csv
import argparse
import numpy as np
import torch
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from matplotlib.ticker import MaxNLocator, FormatStrFormatter, FuncFormatter

import ot
from colors import get_single_color


ONE_MODE_KAPPA_RANGE = (4.0, 8.0)
N_COMPONENTS = 4
MIXTURE_WEIGHTS = np.ones(N_COMPONENTS, dtype=np.float64) / N_COMPONENTS

SHAPE_CASES = ["same", "1_unique", "2_unique", "4_unique"]
MU_LAYOUTS = ["close", "spread", "symmetric"]

# Fast skewed spherical components. The mixture components are generated by
# skewed anisotropic tangent-plane perturbations followed by the S^2 exponential map.
# Thus every returned observation lies on S^2, but the components are not standard vMFs.
MIXTURE_KAPPA_RANGE = (6.0, 28.0)
MIXTURE_BETA_RANGE = (0.35, 1.35)
MIXTURE_SKEW_ABS_RANGE = (1.60, 3.20)
MIXTURE_SKEW_RANGE = (-MIXTURE_SKEW_ABS_RANGE[1], MIXTURE_SKEW_ABS_RANGE[1])
MIXTURE_ANGLE_RANGE = (0.0, np.pi)
MIN_UNIQUE_PARAM_DISTANCE = 0.75
MAX_PARAM_RESAMPLE_ATTEMPTS = 300

CLOSE_RADIUS_RANGE = (0.28, 0.62)
CLOSE_MIN_SEP = 0.10
SPREAD_MIN_SEP_RANGE = (0.85, 1.20)
SYMMETRIC_RADIUS_RANGE = (0.32, 0.85)
SYMMETRIC_RADIUS_JITTER = 0.12

BASELINE_SPECS = [
    {"kind": "uniform", "case": "uniform", "plot_group": "uniform", "shape_case": "baseline", "mu_layout": "baseline"},
    {"kind": "one_vmf", "case": "one_vmf", "plot_group": "one_vmf", "shape_case": "baseline", "mu_layout": "baseline"},
]

SHAPE_LABELS = {
    "uniform": "Uniform", "one_vmf": "1 vMF", "same": "Same",
    "1_unique": "1 unique", "2_unique": "2 unique", "4_unique": "4 unique",
}
MU_LABELS = {"close": "close centers", "spread": "spread centers", "symmetric": "symmetric centers"}
MU_MARKERS = {"close": "o", "spread": "s", "symmetric": "^"}
MU_COLORS = {"close": get_single_color(2), "spread": get_single_color(5), "symmetric": get_single_color(8)}
X_POS = {"uniform": 0.0, "one_vmf": 1.8, "same": 4.0, "1_unique": 5.6, "2_unique": 7.2, "4_unique": 8.8}
LAYOUT_X_OFFSET = {"close": -0.28, "spread": 0.0, "symmetric": 0.28}

LDD_REPRESENTATION_METRICS = [
    ("ldd_variance_source", "LDD variance"),
    ("ldd_effective_rank_source", "LDD effective rank"),
    ("ldd_spectral_entropy_source", "LDD spectral entropy"),
]
ROW_COUPLING_METRICS = [
    ("coupling_row_nonuniformity", "Coupling row non-uniformity"),
    ("coupling_row_peak_ratio_mean", "Coupling row peak ratio"),
]
ALIGNMENT_METRICS = [("rotation_error_deg", "Rotation error (deg)")]
GROUPED_METRICS = LDD_REPRESENTATION_METRICS + ROW_COUPLING_METRICS + ALIGNMENT_METRICS
CORRELATION_METRICS = [m for m, _ in GROUPED_METRICS]
ALIGNMENT_PAIRS = [
    ("ldd_spectral_entropy_source", "rotation_error_deg", "LDD spectral entropy", "Rotation error (deg)", "Spectral entropy vs rotation error"),
    ("coupling_row_nonuniformity", "rotation_error_deg", "Coupling row non-uniformity", "Rotation error (deg)", "Coupling non-uniformity vs rotation error"),
]


def normalize_rows(X, eps=1e-12):
    X = np.asarray(X, dtype=np.float64)
    return X / (np.linalg.norm(X, axis=1, keepdims=True) + eps)


def normalize_vec(x, eps=1e-12):
    x = np.asarray(x, dtype=np.float64)
    return x / (np.linalg.norm(x) + eps)


def assert_on_sphere(Z, name="Z", tol=1e-6):
    Z = np.asarray(Z, dtype=np.float64)
    err = np.max(np.abs(np.linalg.norm(Z, axis=1) - 1.0))
    if err > tol:
        raise ValueError(f"{name} is not on S^2: max |norm-1| = {err:.3e}")
    return float(err)


def tangent_basis(mu):
    mu = normalize_vec(mu)
    ref = np.array([0.0, 0.0, 1.0], dtype=np.float64)
    if abs(float(np.dot(mu, ref))) > 0.92:
        ref = np.array([1.0, 0.0, 0.0], dtype=np.float64)
    e1 = normalize_vec(ref - np.dot(ref, mu) * mu)
    return e1, normalize_vec(np.cross(mu, e1))


def oriented_tangent_basis(mu, angle):
    e1, e2 = tangent_basis(mu)
    c, s = np.cos(angle), np.sin(angle)
    return normalize_vec(c * e1 + s * e2), normalize_vec(-s * e1 + c * e2)


def exp_map_s2(mu, V):
    mu = normalize_vec(mu)
    V = np.asarray(V, dtype=np.float64)
    r = np.linalg.norm(V, axis=1, keepdims=True)
    return normalize_rows(np.cos(r) * mu[None, :] + np.sin(r) * V / np.maximum(r, 1e-12))


def sample_uniform_s2(n, rng):
    return normalize_rows(rng.normal(size=(n, 3)))


def random_rotation_matrix(rng):
    Q, R = np.linalg.qr(rng.normal(size=(3, 3)))
    signs = np.sign(np.diag(R))
    signs[signs == 0.0] = 1.0
    Q = Q @ np.diag(signs)
    if np.linalg.det(Q) < 0:
        Q[:, 0] *= -1.0
    return Q


def rotation_from_north(mu):
    mu = normalize_vec(mu)
    north = np.array([0.0, 0.0, 1.0], dtype=np.float64)
    v = np.cross(north, mu)
    c = float(np.dot(north, mu))
    s = float(np.linalg.norm(v))
    if s < 1e-12:
        return np.eye(3) if c > 0 else np.diag([1.0, -1.0, -1.0])
    K = np.array([[0.0, -v[2], v[1]], [v[2], 0.0, -v[0]], [-v[1], v[0], 0.0]], dtype=np.float64)
    return np.eye(3) + K + K @ K * ((1.0 - c) / s**2)


def sample_vmf_s2(mu, kappa, n, rng):
    mu = normalize_vec(mu)
    if kappa <= 1e-12:
        Z = sample_uniform_s2(n, rng)
        assert_on_sphere(Z, "uniform/vMF sample")
        return Z
    u = rng.uniform(size=n)
    w = np.log(np.exp(-kappa) + u * (np.exp(kappa) - np.exp(-kappa))) / kappa
    phi = rng.uniform(0.0, 2.0 * np.pi, size=n)
    radial = np.sqrt(np.maximum(1.0 - w**2, 0.0))
    X_north = np.column_stack([radial * np.cos(phi), radial * np.sin(phi), w])
    Z = normalize_rows(X_north @ rotation_from_north(mu).T)
    assert_on_sphere(Z, "vMF sample")
    return Z


def centers_close(rng):
    anchor = normalize_vec(rng.normal(size=3))
    e1, e2 = tangent_basis(anchor)
    radius, centers = rng.uniform(*CLOSE_RADIUS_RANGE), []
    for _ in range(20000):
        rho = radius * np.sqrt(rng.uniform())
        phi = rng.uniform(0.0, 2.0 * np.pi)
        z = exp_map_s2(anchor, (rho * np.cos(phi) * e1 + rho * np.sin(phi) * e2)[None, :])[0]
        if len(centers) == 0 or np.min(np.arccos(np.clip(np.asarray(centers) @ z, -1.0, 1.0))) >= CLOSE_MIN_SEP:
            centers.append(z)
        if len(centers) == N_COMPONENTS:
            return normalize_rows(np.asarray(centers)), {"center_radius": float(radius)}
    raise RuntimeError("Could not sample close centers.")


def centers_spread(rng):
    min_sep, centers = rng.uniform(*SPREAD_MIN_SEP_RANGE), []
    for _ in range(30000):
        x = sample_uniform_s2(1, rng)[0]
        if len(centers) == 0 or np.min(np.arccos(np.clip(np.asarray(centers) @ x, -1.0, 1.0))) >= min_sep:
            centers.append(x)
        if len(centers) == N_COMPONENTS:
            return normalize_rows(np.asarray(centers)), {"center_min_sep": float(min_sep)}
    raise RuntimeError("Could not sample spread centers.")


def centers_symmetric(rng):
    anchor = normalize_vec(rng.normal(size=3))
    e1, e2 = tangent_basis(anchor)
    radius, phase = rng.uniform(*SYMMETRIC_RADIUS_RANGE), rng.uniform(0.0, 2.0 * np.pi)
    centers = []
    for k in range(N_COMPONENTS):
        phi = phase + 2.0 * np.pi * k / N_COMPONENTS
        rho = radius * (1.0 + rng.uniform(-SYMMETRIC_RADIUS_JITTER, SYMMETRIC_RADIUS_JITTER))
        centers.append(exp_map_s2(anchor, (rho * np.cos(phi) * e1 + rho * np.sin(phi) * e2)[None, :])[0])
    return normalize_rows(np.asarray(centers)), {"center_radius": float(radius)}


def centers_for_layout(mu_layout, rng):
    return {"close": centers_close, "spread": centers_spread, "symmetric": centers_symmetric}[mu_layout](rng)


def sample_component_params(rng):
    skew_abs = rng.uniform(*MIXTURE_SKEW_ABS_RANGE)
    skew_sign = -1.0 if rng.uniform() < 0.5 else 1.0
    return {
        "kappa": float(rng.uniform(*MIXTURE_KAPPA_RANGE)),
        "beta": float(rng.uniform(*MIXTURE_BETA_RANGE)),
        "skew": float(skew_sign * skew_abs),
        "angle": float(rng.uniform(*MIXTURE_ANGLE_RANGE)),
    }


def component_param_distance(a, b):
    d_angle = abs(a["angle"] - b["angle"])
    d_angle = min(d_angle, np.pi - d_angle) / np.pi
    return float(np.sqrt(np.log(a["kappa"] / b["kappa"])**2 + (a["beta"] - b["beta"])**2 + (a["skew"] - b["skew"])**2 + d_angle**2))


def sample_component_param_distinct_from_many(rng, refs):
    candidate = None
    for _ in range(MAX_PARAM_RESAMPLE_ATTEMPTS):
        candidate = sample_component_params(rng)
        if all(component_param_distance(candidate, ref) >= MIN_UNIQUE_PARAM_DISTANCE for ref in refs):
            return candidate
    return candidate


def choose_unique_indices(shape_case, rng):
    if shape_case == "same":
        return tuple()
    if shape_case == "1_unique":
        return tuple(sorted(rng.choice(N_COMPONENTS, size=1, replace=False).tolist()))
    if shape_case == "2_unique":
        return tuple(sorted(rng.choice(N_COMPONENTS, size=2, replace=False).tolist()))
    if shape_case == "4_unique":
        return tuple(range(N_COMPONENTS))
    raise ValueError(f"Unknown shape_case: {shape_case}")


def component_params(shape_case, rng):
    unique_idx = choose_unique_indices(shape_case, rng)
    if shape_case == "same":
        shared = sample_component_params(rng)
        return [dict(shared) for _ in range(N_COMPONENTS)], unique_idx
    if shape_case in ["1_unique", "2_unique"]:
        shared = sample_component_params(rng)
        params, refs = [dict(shared) for _ in range(N_COMPONENTS)], [shared]
        for idx in unique_idx:
            params[idx] = sample_component_param_distinct_from_many(rng, refs)
            refs.append(params[idx])
        return params, unique_idx
    params = []
    for _ in range(N_COMPONENTS):
        params.append(sample_component_param_distinct_from_many(rng, params))
    return params, unique_idx


def sample_skewed_spherical_component(mu, params, n, rng):
    """Skewed anisotropic tangent perturbations mapped to S^2 by the exponential map."""
    a1, a2 = oriented_tangent_basis(mu, params["angle"])
    kappa, beta, skew = float(params["kappa"]), float(params["beta"]), float(params["skew"])
    base_scale = 1.0 / np.sqrt(kappa)
    s1 = base_scale * np.exp(0.35 * beta)
    s2 = base_scale * np.exp(-0.35 * beta)
    delta = np.clip(skew / np.sqrt(1.0 + skew**2), -0.985, 0.985)
    z0, z1, z2 = rng.normal(size=(3, n))
    u = s1 * (delta * np.abs(z0) + np.sqrt(1.0 - delta**2) * z1)
    v = s2 * z2
    u -= 0.25 * np.mean(u)
    V = u[:, None] * a1[None, :] + v[:, None] * a2[None, :]
    Z = exp_map_s2(mu, V)
    assert_on_sphere(Z, "skewed spherical component")
    return Z


def build_specs(gallery=False):
    specs = [dict(s) for s in BASELINE_SPECS]
    outer, inner = (SHAPE_CASES, MU_LAYOUTS) if gallery else (MU_LAYOUTS, SHAPE_CASES)
    for a in outer:
        for b in inner:
            shape_case, mu_layout = (a, b) if gallery else (b, a)
            prefix = "gallery" if gallery else "mm"
            specs.append({
                "kind": "mixture",
                "case": f"{prefix}_{mu_layout}_{shape_case}",
                "plot_group": f"{mu_layout}_{shape_case}",
                "shape_case": shape_case,
                "mu_layout": mu_layout,
            })
    return specs


def materialize_distribution_design(spec, design_seed):
    rng = np.random.default_rng(design_seed)
    if spec["kind"] == "one_vmf":
        return {"mu": sample_uniform_s2(1, rng)[0], "kappa": float(rng.uniform(*ONE_MODE_KAPPA_RANGE))}
    if spec["kind"] == "mixture":
        mus, center_info = centers_for_layout(spec["mu_layout"], rng)
        params, unique_idx = component_params(spec["shape_case"], rng)
        return {"mus": mus, "params": params, "center_info": center_info, "unique_idx": unique_idx}
    return None


def sample_distribution(spec, n, rng, design=None):
    if spec["kind"] == "uniform":
        Z = sample_uniform_s2(n, rng)
        assert_on_sphere(Z, "uniform sample")
        return Z, -np.ones(n, dtype=np.int64), None, None
    if spec["kind"] == "one_vmf":
        Z = sample_vmf_s2(design["mu"], design["kappa"], n, rng)
        assert_on_sphere(Z, "one-vMF sample")
        return Z, np.zeros(n, dtype=np.int64), None, None
    mus, params = design["mus"], design["params"]
    labels = rng.choice(N_COMPONENTS, size=n, p=MIXTURE_WEIGHTS)
    Z = np.zeros((n, 3), dtype=np.float64)
    for k in range(N_COMPONENTS):
        idx = np.where(labels == k)[0]
        if len(idx):
            Z[idx] = sample_skewed_spherical_component(mus[k], params[k], len(idx), rng)
    Z = normalize_rows(Z)
    assert_on_sphere(Z, "four-mode spherical mixture sample")
    return Z, labels, mus, params


def spec_offset(spec):
    if spec["kind"] == "uniform":
        return 11
    if spec["kind"] == "one_vmf":
        return 23
    return {"close": 1000, "spread": 2000, "symmetric": 3000}[spec["mu_layout"]] + {"same": 10, "1_unique": 20, "2_unique": 30, "4_unique": 40}[spec["shape_case"]]


def sample_independent_pair(spec, n, seed_a, seed_b, seed_rot, design_seed):
    design = materialize_distribution_design(spec, design_seed)
    Z_a, labels_a, mus, params = sample_distribution(spec, n, np.random.default_rng(seed_a), design)
    Z_b0, labels_b, _, _ = sample_distribution(spec, n, np.random.default_rng(seed_b), design)
    R_star = random_rotation_matrix(np.random.default_rng(seed_rot))
    Z_b = normalize_rows(Z_b0 @ R_star.T)
    assert_on_sphere(Z_a, "Z_a")
    assert_on_sphere(Z_b, "Z_b")
    if spec["kind"] == "mixture":
        center_info, unique_idx, one_vmf_info = design["center_info"], design["unique_idx"], {}
    elif spec["kind"] == "one_vmf":
        center_info, unique_idx = {}, tuple()
        one_vmf_info = {"one_vmf_kappa": design["kappa"], "one_vmf_mu": design["mu"]}
    else:
        center_info, unique_idx, one_vmf_info = {}, tuple(), {}
    return Z_a, Z_b, labels_a, labels_b, R_star, mus, params, center_info, unique_idx, one_vmf_info


def distance_geo_arccos(Z):
    Z = normalize_rows(Z)
    assert_on_sphere(Z, "distance input")
    return np.arccos(np.clip(Z @ Z.T, -1.0, 1.0))


def make_radii(r_min, r_max, r_bins, radius_grid):
    if r_min <= 0 or r_max <= r_min:
        raise ValueError("Require 0 < r_min < r_max.")
    if radius_grid == "log":
        return np.logspace(np.log10(float(r_min)), np.log10(float(r_max)), int(r_bins))
    if radius_grid == "linear":
        return np.linspace(float(r_min), float(r_max), int(r_bins))
    raise ValueError(f"Unknown radius_grid: {radius_grid}")


def compute_ldd(D, radii):
    D = np.asarray(D, dtype=np.float64).copy()
    n = D.shape[0]
    if D.shape != (n, n):
        raise ValueError(f"D must have shape (n,n), got {D.shape}")
    np.fill_diagonal(D, np.inf)
    D_sorted = np.sort(D, axis=1)
    H = np.empty((n, len(radii)), dtype=np.float32)
    for i in range(n):
        H[i] = np.searchsorted(D_sorted[i], radii, side="right") / (n - 1)
    return torch.from_numpy(H).float()


def compute_ldd_cost(H_a, H_b):
    return torch.cdist(torch.as_tensor(H_a, dtype=torch.float32), torch.as_tensor(H_b, dtype=torch.float32), p=2) ** 2


def ldd_diagnostics(H, rank_tol=1e-10, eps=1e-12):
    H = torch.as_tensor(H, dtype=torch.float64)
    Hc = H - H.mean(dim=0, keepdim=True)
    variance = float((Hc**2).mean().item())
    svals = torch.clamp(torch.linalg.svdvals(H), min=0.0)
    total = svals.sum()
    r = min(H.shape)
    if total <= eps:
        return {"ldd_variance": variance, "ldd_matrix_rank": 0.0, "ldd_spectral_entropy": np.nan, "ldd_effective_rank": np.nan}
    p = svals / total
    entropy = -(p * torch.log(p + eps)).sum()
    return {
        "ldd_variance": variance,
        "ldd_matrix_rank": float((svals > float(rank_tol) * float(svals.max().item())).sum().item()),
        "ldd_spectral_entropy": float((entropy / np.log(r)).item()) if r > 1 else 0.0,
        "ldd_effective_rank": float(torch.exp(entropy).item()),
    }


def source_ldd_metrics(diag_a):
    return {f"{k}_source": v for k, v in diag_a.items()}


def init_sinkhorn(M, epsilon, num_itermax, stop_thr=1e-7, warn=False):
    M_np = torch.as_tensor(M, dtype=torch.float64).detach().cpu().numpy()
    n_a, n_b = M_np.shape
    a, b = np.ones(n_a) / n_a, np.ones(n_b) / n_b
    P = ot.sinkhorn(a, b, M_np, reg=float(epsilon), numItermax=int(num_itermax), stopThr=float(stop_thr), warn=warn)
    return torch.from_numpy(P).float()


def sinkhorn_diagnostics(P):
    P = torch.as_tensor(P, dtype=torch.float64)
    n, m = P.shape
    return {
        "sinkhorn_total_mass": float(P.sum().item()),
        "sinkhorn_row_marginal_max_error": float(torch.max(torch.abs(P.sum(dim=1) - 1.0 / n)).item()),
        "sinkhorn_col_marginal_max_error": float(torch.max(torch.abs(P.sum(dim=0) - 1.0 / m)).item()),
    }


def row_coupling_diagnostics(P, eps=1e-12):
    P = torch.as_tensor(P, dtype=torch.float32)
    n_a, n_b = P.shape
    Q = P / (P.sum(dim=1, keepdim=True) + eps)
    uniform_value = 1.0 / n_b
    peak_ratio = Q.max(dim=1).values / uniform_value
    row_entropy = -(Q * torch.log(Q + eps)).sum(dim=1)
    return {
        "coupling_row_nonuniformity": float(((Q - uniform_value) ** 2).sum().item() / n_a),
        "coupling_row_peak_ratio_mean": float(peak_ratio.mean().item()),
        "coupling_row_peak_ratio_std": float(peak_ratio.std().item()),
        "coupling_row_entropy_mean": float(row_entropy.mean().item()),
        "coupling_row_entropy_std": float(row_entropy.std().item()),
    }


def fit_rotation_from_coupling(X_src, X_tgt, P):
    C = np.asarray(X_tgt, dtype=np.float64).T @ np.asarray(P, dtype=np.float64).T @ np.asarray(X_src, dtype=np.float64)
    U, _, Vt = np.linalg.svd(C, full_matrices=True)
    R = U @ Vt
    if np.linalg.det(R) < 0:
        U[:, -1] *= -1.0
        R = U @ Vt
    return R


def rotation_angle_error_deg(R_hat, R_true):
    val = (np.trace(np.asarray(R_hat).T @ np.asarray(R_true)) - 1.0) / 2.0
    return float(np.degrees(np.arccos(np.clip(val, -1.0, 1.0))))


def alignment_diagnostics_from_coupling(X_src, X_tgt, P, R_star):
    R_hat = fit_rotation_from_coupling(X_src, X_tgt, P)
    return {"rotation_error_deg": rotation_angle_error_deg(R_hat, R_star), "rotation_det_est": float(np.linalg.det(R_hat))}


def seed_bundle(args, rep, spec):
    offset = spec_offset(spec)
    base = args.seed + 10000 * rep + offset
    return {"seed_a": base + 17, "seed_b": base + 29, "seed_rot": base + 101, "design_seed": args.design_seed + 10000 * rep + offset}


def base_row(spec, rep, seeds, args, r_max, M):
    return {
        **{k: spec[k] for k in ["kind", "case", "plot_group", "shape_case", "mu_layout"]},
        **seeds,
        "rep": int(rep),
        "distance_type": "geo_arccos",
        "radius_grid": args.radius_grid,
        "n_points": int(args.n_points),
        "r_bins": int(args.r_bins),
        "r_min": float(args.r_min),
        "r_max": float(r_max),
        "sinkhorn_epsilon": float(args.sinkhorn_epsilon),
        "sinkhorn_iter": int(args.sinkhorn_iter),
        "sinkhorn_stop_thr": float(args.sinkhorn_stop_thr),
        "M_mean": float(M.mean().item()),
        "M_std": float(M.std().item()),
        "M_max": float(M.max().item()),
        "one_vmf_kappa_min": float(ONE_MODE_KAPPA_RANGE[0]),
        "one_vmf_kappa_max": float(ONE_MODE_KAPPA_RANGE[1]),
        "mixture_kappa_min": float(MIXTURE_KAPPA_RANGE[0]),
        "mixture_kappa_max": float(MIXTURE_KAPPA_RANGE[1]),
        "mixture_beta_min": float(MIXTURE_BETA_RANGE[0]),
        "mixture_beta_max": float(MIXTURE_BETA_RANGE[1]),
        "mixture_skew_min": float(MIXTURE_SKEW_RANGE[0]),
        "mixture_skew_max": float(MIXTURE_SKEW_RANGE[1]),
    }


def add_design_info(row, spec, mus, params, center_info, unique_idx, one_vmf_info):
    row["unique_idx"] = "none" if len(unique_idx) == 0 else "-".join(str(i + 1) for i in unique_idx)
    row["unique_count"] = int(len(unique_idx)) if spec["kind"] == "mixture" else (-2 if spec["kind"] == "uniform" else -1)
    if spec["kind"] == "one_vmf":
        row["one_vmf_kappa"] = float(one_vmf_info["one_vmf_kappa"])
        row.update({f"one_vmf_mu_{ax}": float(v) for ax, v in zip(["x", "y", "z"], one_vmf_info["one_vmf_mu"])})
    if spec["kind"] == "mixture":
        row.update({f"mixture_weight_{i + 1}": float(w) for i, w in enumerate(MIXTURE_WEIGHTS)})
        row.update({k: float(v) for k, v in center_info.items()})
        for k, par in enumerate(params):
            row.update({
                f"component{k + 1}_kappa": float(par["kappa"]),
                f"component{k + 1}_beta": float(par["beta"]),
                f"component{k + 1}_skew": float(par["skew"]),
                f"component{k + 1}_angle": float(par["angle"]),
                f"component{k + 1}_is_unique": int(k in unique_idx),
                f"mu{k + 1}_x": float(mus[k, 0]),
                f"mu{k + 1}_y": float(mus[k, 1]),
                f"mu{k + 1}_z": float(mus[k, 2]),
            })


def run_one(spec, rep, args):
    seeds = seed_bundle(args, rep, spec)
    Z_a, Z_b, _, _, R_star, mus, params, center_info, unique_idx, one_vmf_info = sample_independent_pair(
        spec, args.n_points, seeds["seed_a"], seeds["seed_b"], seeds["seed_rot"], seeds["design_seed"]
    )
    D_a, D_b = distance_geo_arccos(Z_a), distance_geo_arccos(Z_b)
    r_max = float(max(D_a.max(), D_b.max())) if args.r_max is None else float(args.r_max)
    radii = make_radii(args.r_min, r_max, args.r_bins, args.radius_grid)
    H_a, H_b = compute_ldd(D_a, radii), compute_ldd(D_b, radii)
    M = compute_ldd_cost(H_a, H_b)
    P = init_sinkhorn(M, args.sinkhorn_epsilon, args.sinkhorn_iter, args.sinkhorn_stop_thr, args.sinkhorn_warn)

    diag_a = ldd_diagnostics(H_a, args.ldd_rank_tol)
    diag_b = ldd_diagnostics(H_b, args.ldd_rank_tol)
    row = base_row(spec, rep, seeds, args, r_max, M)
    row["sphere_norm_error_A"] = assert_on_sphere(Z_a, "Z_a")
    row["sphere_norm_error_B"] = assert_on_sphere(Z_b, "Z_b")
    add_design_info(row, spec, mus, params, center_info, unique_idx, one_vmf_info)
    row.update({f"A_{k}": v for k, v in diag_a.items()})
    row.update({f"B_{k}": v for k, v in diag_b.items()})
    row.update(source_ldd_metrics(diag_a))
    row.update(sinkhorn_diagnostics(P))
    row.update(row_coupling_diagnostics(P))
    row.update(alignment_diagnostics_from_coupling(Z_a, Z_b, P.detach().cpu().numpy(), R_star))
    return row


def write_csv(rows, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    keys = sorted({k for row in rows for k in row.keys()})
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)


def save_grouped_csv(rows, path):
    group_fields = ["kind", "shape_case", "mu_layout", "plot_group", "distance_type", "radius_grid"]
    grouped = {}
    for row in rows:
        grouped.setdefault(tuple(row[k] for k in group_fields), []).append(row)
    out_rows = []
    for key, group in grouped.items():
        out = {k: v for k, v in zip(group_fields, key)}
        out["n"] = len(group)
        for metric, _ in GROUPED_METRICS:
            vals = np.asarray([float(g.get(metric, np.nan)) for g in group], dtype=np.float64)
            vals = vals[np.isfinite(vals)]
            out[f"{metric}_mean"] = float(vals.mean()) if len(vals) else np.nan
            out[f"{metric}_std"] = float(vals.std(ddof=1)) if len(vals) > 1 else (0.0 if len(vals) == 1 else np.nan)
        out_rows.append(out)
    write_csv(out_rows, path)


def corr(x, y):
    mask = np.isfinite(x) & np.isfinite(y)
    x, y = x[mask], y[mask]
    if len(x) < 2 or np.std(x) <= 0.0 or np.std(y) <= 0.0:
        return np.nan
    return float(np.corrcoef(x, y)[0, 1])


def save_correlation_csv(rows, path):
    values = {m: np.asarray([float(r.get(m, np.nan)) for r in rows], dtype=np.float64) for m in CORRELATION_METRICS}
    out = [{"metric": x, **{y: corr(values[x], values[y]) for y in CORRELATION_METRICS}} for x in CORRELATION_METRICS]
    write_csv(out, path)


def row_color(row):
    if row["kind"] == "uniform":
        return "black"
    if row["kind"] == "one_vmf":
        return get_single_color(7)
    return MU_COLORS[row["mu_layout"]]


def row_marker(row):
    if row["kind"] == "uniform":
        return "X"
    if row["kind"] == "one_vmf":
        return "D"
    return MU_MARKERS[row["mu_layout"]]


def x_for_row(row):
    return X_POS[row["plot_group"]] if row["kind"] in ["uniform", "one_vmf"] else X_POS[row["shape_case"]]


def jitter_for_row(row):
    if row["kind"] in ["uniform", "one_vmf"]:
        return 0.035 * (int(row["rep"]) - 0.5)
    return LAYOUT_X_OFFSET[row["mu_layout"]] + 0.026 * int(row["rep"])


def set_shape_axis(ax):
    order = ["uniform", "one_vmf"] + SHAPE_CASES
    ax.set_xticks([X_POS[x] for x in order])
    ax.set_xticklabels([SHAPE_LABELS[x] for x in order], rotation=25, ha="right")
    ax.margins(x=0.035)


def add_main_legend(fig, y=0.95):
    handles = [
        plt.Line2D([0], [0], marker=MU_MARKERS[l], color=MU_COLORS[l], linestyle="none", markeredgecolor="black", markersize=8, label=MU_LABELS[l])
        for l in MU_LAYOUTS
    ]
    handles += [
        plt.Line2D([0], [0], marker="X", color="black", linestyle="none", markeredgecolor="black", markersize=8, label="Uniform"),
        plt.Line2D([0], [0], marker="D", color=get_single_color(7), linestyle="none", markeredgecolor="black", markersize=8, label="1 vMF"),
    ]
    fig.legend(handles=handles, loc="upper center", bbox_to_anchor=(0.5, y), ncol=5, frameon=False, fontsize=10.5)


def group_keys():
    return [("uniform", "baseline", "baseline"), ("one_vmf", "baseline", "baseline")] + [("mixture", s, l) for s in SHAPE_CASES for l in MU_LAYOUTS]


def rows_for_group(rows, kind, shape_case, mu_layout):
    return [r for r in rows if r["kind"] == kind and (kind != "mixture" or (r["shape_case"] == shape_case and r["mu_layout"] == mu_layout))]


def aggregate_for_metric(rows, metric):
    groups = []
    for kind, shape_case, mu_layout in group_keys():
        vals = np.asarray([float(r.get(metric, np.nan)) for r in rows_for_group(rows, kind, shape_case, mu_layout)], dtype=np.float64)
        vals = vals[np.isfinite(vals)]
        if len(vals):
            groups.append({
                "row": {"kind": kind, "shape_case": shape_case, "mu_layout": mu_layout, "plot_group": kind if kind != "mixture" else f"{mu_layout}_{shape_case}", "rep": 0},
                "mean": float(vals.mean()),
                "std": float(vals.std(ddof=1)) if len(vals) > 1 else 0.0,
            })
    return groups


def aggregate_for_pair(rows, x_key, y_key):
    groups = []
    for kind, shape_case, mu_layout in group_keys():
        xy = np.asarray([
            [float(r.get(x_key, np.nan)), float(r.get(y_key, np.nan))]
            for r in rows_for_group(rows, kind, shape_case, mu_layout)
        ], dtype=np.float64)
        xy = xy[np.isfinite(xy).all(axis=1)] if len(xy) else xy
        if len(xy):
            groups.append({
                "row": {"kind": kind, "shape_case": shape_case, "mu_layout": mu_layout, "plot_group": kind if kind != "mixture" else f"{mu_layout}_{shape_case}", "rep": 0},
                "x": float(xy[:, 0].mean()),
                "y": float(xy[:, 1].mean()),
                "xstd": float(xy[:, 0].std(ddof=1)) if len(xy) > 1 else 0.0,
                "ystd": float(xy[:, 1].std(ddof=1)) if len(xy) > 1 else 0.0,
            })
    return groups


def plot_metric_row(rows, metrics, save_path, suptitle, figsize):
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    fig, axes = plt.subplots(1, len(metrics), figsize=figsize, squeeze=False)
    for ax, (metric, title) in zip(axes.ravel(), metrics):
        for row in rows:
            y = float(row.get(metric, np.nan))
            if np.isfinite(y):
                ax.scatter(x_for_row(row) + jitter_for_row(row), y, s=24, alpha=0.16, color=row_color(row), marker=row_marker(row), edgecolors="none")
        for item in aggregate_for_metric(rows, metric):
            row = item["row"]
            x = x_for_row(row) + (LAYOUT_X_OFFSET[row["mu_layout"]] if row["kind"] == "mixture" else 0.0)
            ax.errorbar(x, item["mean"], yerr=item["std"], fmt=row_marker(row), color=row_color(row), markeredgecolor="black", markeredgewidth=0.8, markersize=7.5, linewidth=1.15, capsize=3, alpha=0.96)
        set_shape_axis(ax)
        ax.yaxis.set_major_locator(MaxNLocator(nbins=5))
        ax.set_title(title, fontsize=12.5, pad=9)
        ax.grid(alpha=0.22)
    fig.suptitle(suptitle, fontsize=18, y=0.99)
    add_main_legend(fig, y=0.91)
    fig.subplots_adjust(top=0.76, bottom=0.22, left=0.065, right=0.985, wspace=0.30)
    plt.savefig(save_path, dpi=220)
    plt.close()


def _format_alignment_axis(ax, x_key):
    ax.yaxis.set_major_locator(MaxNLocator(nbins=5))
    ax.xaxis.set_major_locator(MaxNLocator(nbins=5))
    if x_key == "ldd_spectral_entropy_source":
        ax.xaxis.set_major_formatter(FormatStrFormatter("%.2f"))
    elif x_key == "coupling_row_nonuniformity":
        ax.xaxis.set_major_formatter(FuncFormatter(lambda x, pos: f"{1000.0 * x:.1f}"))
        ax.set_xlabel(r"Coupling row non-uniformity ($\times 10^{-3}$)")


def plot_scatter_grid(rows, pairs, nrows, ncols, save_path, suptitle, figsize):
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    fig, axes = plt.subplots(nrows, ncols, figsize=figsize, squeeze=False)
    flat_axes = axes.ravel()
    for ax, (x_key, y_key, x_lab, y_lab, title) in zip(flat_axes, pairs):
        y_max = 0.0
        for row in rows:
            x, y = float(row.get(x_key, np.nan)), float(row.get(y_key, np.nan))
            if np.isfinite(x) and np.isfinite(y):
                y_max = max(y_max, y)
                ax.scatter(x, y, s=42, alpha=0.30, color=row_color(row), marker=row_marker(row), edgecolors="black", linewidths=0.55)
        for item in aggregate_for_pair(rows, x_key, y_key):
            row = item["row"]
            x_lower = min(item["xstd"], max(item["x"], 0.0))
            y_lower = min(item["ystd"], max(item["y"], 0.0))
            ax.errorbar(
                item["x"], item["y"],
                xerr=np.array([[x_lower], [item["xstd"]]]),
                yerr=np.array([[y_lower], [item["ystd"]]]),
                fmt=row_marker(row), color=row_color(row), markeredgecolor="black", markeredgewidth=0.9,
                markersize=8.0, linewidth=1.35, capsize=3.5, alpha=0.98, zorder=5,
            )
            y_max = max(y_max, item["y"] + item["ystd"])
        ax.set_xlabel(x_lab)
        ax.set_ylabel(y_lab)
        ax.set_title(title, fontsize=11.5, pad=8)
        ax.grid(alpha=0.22)
        ax.set_ylim(bottom=-0.03 * max(y_max, 1.0))
        ax.margins(x=0.06, y=0.06)
        _format_alignment_axis(ax, x_key)
    for ax in flat_axes[len(pairs):]:
        ax.axis("off")
    fig.suptitle(suptitle, fontsize=18, y=0.99)
    add_main_legend(fig, y=0.91)
    fig.subplots_adjust(top=0.76, bottom=0.18, left=0.07, right=0.985, hspace=0.35, wspace=0.30)
    plt.savefig(save_path, dpi=220)
    plt.close()


def plot_sphere_points(ax, Z, labels, title):
    u, v = np.linspace(0, 2.0 * np.pi, 32), np.linspace(0.0, np.pi, 16)
    ax.plot_wireframe(np.outer(np.cos(u), np.sin(v)), np.outer(np.sin(u), np.sin(v)), np.outer(np.ones_like(u), np.cos(v)), linewidth=0.20, alpha=0.12)
    if np.all(labels < 0):
        ax.scatter(Z[:, 0], Z[:, 1], Z[:, 2], s=5, alpha=0.38, color=get_single_color(0), depthshade=False)
    else:
        for k in sorted(set(labels.tolist())):
            idx = labels == k
            ax.scatter(Z[idx, 0], Z[idx, 1], Z[idx, 2], s=5, alpha=0.48, color=get_single_color(k + 2), depthshade=False)
    ax.set_title(title, fontsize=8.5, pad=2)
    ax.set_box_aspect([1, 1, 1])
    ax.set_xlim([-1.05, 1.05])
    ax.set_ylim([-1.05, 1.05])
    ax.set_zlim([-1.05, 1.05])
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_zticks([])


def gallery_title(spec):
    return SHAPE_LABELS[spec["plot_group"]] if spec["kind"] in ["uniform", "one_vmf"] else f"{spec['mu_layout']} / {SHAPE_LABELS[spec['shape_case']]}"


def plot_distribution_gallery_for_rep(save_path, n_plot, rep, args):
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    specs = build_specs(gallery=True)
    fig = plt.figure(figsize=(15.0, 17.5))
    gs = GridSpec(5, 6, figure=fig, height_ratios=[1.0, 1.05, 1.05, 1.05, 1.05], hspace=0.10, wspace=0.02)
    for i, spec in enumerate(specs[:2]):
        ax = fig.add_subplot([gs[0, 1:3], gs[0, 3:5]][i], projection="3d")
        offset = spec_offset(spec)
        design = materialize_distribution_design(spec, args.design_seed + 10000 * rep + offset)
        Z, labels, _, _ = sample_distribution(spec, n_plot, np.random.default_rng(args.seed + 10000 * rep + offset + 707), design)
        plot_sphere_points(ax, Z, labels, gallery_title(spec))
    for idx, spec in enumerate(specs[2:]):
        ax = fig.add_subplot(gs[1 + idx // 3, 2 * (idx % 3):2 * (idx % 3) + 2], projection="3d")
        offset = spec_offset(spec)
        design = materialize_distribution_design(spec, args.design_seed + 10000 * rep + offset)
        Z, labels, _, _ = sample_distribution(spec, n_plot, np.random.default_rng(args.seed + 10000 * rep + offset + 707), design)
        plot_sphere_points(ax, Z, labels, gallery_title(spec))
    fig.suptitle(f"Distribution gallery, run {rep}", fontsize=16, y=0.995)
    fig.subplots_adjust(left=0.02, right=0.98, top=0.975, bottom=0.015)
    plt.savefig(save_path, dpi=220, bbox_inches="tight")
    plt.close()


def main(args):
    plot_root, csv_root = os.path.join(args.out_root, "plots"), os.path.join(args.out_root, "csv")
    os.makedirs(plot_root, exist_ok=True)
    os.makedirs(csv_root, exist_ok=True)

    rows = []
    for spec in build_specs(gallery=False):
        for rep in range(args.n_reps):
            rows.append(run_one(spec, rep, args))

    results_csv = os.path.join(csv_root, "sensitivity_results.csv")
    grouped_csv = os.path.join(csv_root, "sensitivity_grouped_summary.csv")
    corr_csv = os.path.join(csv_root, "sensitivity_metric_correlations.csv")
    write_csv(rows, results_csv)
    save_grouped_csv(rows, grouped_csv)
    save_correlation_csv(rows, corr_csv)

    p1 = os.path.join(plot_root, "01_ldd_representation_1x3.png")
    p2 = os.path.join(plot_root, "02_coupling_response_1x2.png")
    p3 = os.path.join(plot_root, "03_downstream_alignment_1x2.png")
    plot_metric_row(rows, LDD_REPRESENTATION_METRICS, p1, "LDD representation metrics", figsize=(14.5, 4.8))
    plot_metric_row(rows, ROW_COUPLING_METRICS, p2, "Coupling response metrics", figsize=(10.2, 4.8))
    plot_scatter_grid(rows, ALIGNMENT_PAIRS, 1, 2, p3, "Downstream alignment check", figsize=(11.6, 4.8))

    gallery_paths = []
    if args.save_sphere_gallery:
        for rep in range(args.gallery_reps):
            gallery_path = os.path.join(plot_root, f"00_distribution_gallery_run_{rep:02d}.png")
            plot_distribution_gallery_for_rep(gallery_path, args.n_plot_sphere, rep, args)
            gallery_paths.append(gallery_path)

    print("\nSaved CSV files:")
    print(results_csv)
    print(grouped_csv)
    print(corr_csv)

    print("\nSaved plots:")
    for path in gallery_paths + [p1, p2, p3]:
        print(path)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-root", type=str, default="sensitivity")
    parser.add_argument("--n-points", type=int, default=2000)
    parser.add_argument("--n-reps", type=int, default=5)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--design-seed", type=int, default=777)
    parser.add_argument("--radius-grid", type=str, default="log", choices=["log", "linear"])
    parser.add_argument("--r-bins", type=int, default=100)
    parser.add_argument("--r-min", type=float, default=1e-4)
    parser.add_argument("--r-max", type=float, default=None)
    parser.add_argument("--sinkhorn-epsilon", type=float, default=0.05)
    parser.add_argument("--sinkhorn-iter", type=int, default=2000)
    parser.add_argument("--sinkhorn-stop-thr", type=float, default=1e-7)
    parser.add_argument("--sinkhorn-warn", action="store_true")
    parser.add_argument("--ldd-rank-tol", type=float, default=1e-10)
    parser.add_argument("--save-sphere-gallery", action="store_true")
    parser.add_argument("--gallery-reps", type=int, default=2)
    parser.add_argument("--n-plot-sphere", type=int, default=650)
    return parser.parse_args()


if __name__ == "__main__":
    main(parse_args())
